env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  import/extensions: [
     "error",
     "ignorePackages",
     {
       "js": "never",
       "jsx": "never",
       "ts": "never",
       "tsx": "never"
     }
  ]
  indent: "off"
  semi: "off"
  "@typescript-eslint/semi": ["off"]
  no-console: "off"
settings:
  import/resolver:
    typescript:
      project: './src/oms'

