env:
  browser: true
  es2021: true
  node: true
extends:
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  quotes: ["warn", "single"]
  object-curly-spacing: ["warn", "always"]
  indent: ["error", 4]
  semi: "off"
  "@typescript-eslint/semi": ["off"]
  no-console: "off"
  "camelcase": "off"
  "@typescript-eslint/naming-convention": [
    "error",
    {
      "selector": "default",
      "format": ["camelCase"],
    },
    {
      "selector": "property",
      "format": ["camelCase", "snake_case"],
    },
    {
      selector: 'typeLike',
      format: ['PascalCase'],
    },
  ]
  eqeqeq: ["warn", "smart"]
  arrow-parens: ["warn", "as-needed"]
settings:
  import/resolver:
    typescript:
      project: './src/oms'

