---
- project:
    merge-mode: squash-merge
    check:
      jobs:
        - simple
    gate:
      jobs:
        - simple

- job:
    name: "simple"
    parent: "simpleton"
    nodeset: ubuntu-jammy
    vars:
      simple_source_image: "node:20"
      simple_prerun:
        - yarn install
      simple_run:
        - yarn lint
        - yarn build
        - yarn unit
        - yarn integration
