---
- project:
    merge-mode: squash-merge
    check:
      jobs:
      - job:
        name: simple
        vars:
          simple_run:
          - yarn lint
          - yarn build
          - yarn unit
          - yarn intergation
          - yarn cov-merge
          - yarn cov-report:codecov
    gate:
      jobs:
      - job:
        name: simple
        vars:
          simple_env:
            OS_TOKEN: os_token
          simple_run:
          - yarn lint
          - yarn build
          - yarn test
          - yarn cov-merge
          - yarn cov-report:codecov

- job:
    name: "simple"
    parent: "simpleton"
    vars:
      simple_source_image: "npm:latest"
      simple_prerun:
      - yarn install
    secrets:
    - name: os_token
      secret: ...
